version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sethlinarees@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
