// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeniorProjBackend.Data;

#nullable disable

namespace SeniorProjBackend.Migrations
{
    [DbContext(typeof(OurDbContext))]
    partial class OurDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeniorProjBackend.Data.AIConversation", b =>
                {
                    b.Property<int>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationID"));

                    b.Property<string>("ConversationContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ProblemID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ConversationID");

                    b.HasIndex("ProblemID");

                    b.HasIndex("UserID");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.APIKey", b =>
                {
                    b.Property<int>("APIKeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("APIKeyID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Permissions")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("APIKeyID");

                    b.HasIndex("UserID");

                    b.ToTable("APIKeys");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("AuditLogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProblemID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmissionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackID");

                    b.HasIndex("ProblemID");

                    b.HasIndex("UserID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageID"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Problem", b =>
                {
                    b.Property<int>("ProblemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProblemID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("TestCodeFileName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("ProblemID");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.ProblemCategory", b =>
                {
                    b.Property<int>("ProblemCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProblemCategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemID")
                        .HasColumnType("integer");

                    b.HasKey("ProblemCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProblemID");

                    b.ToTable("ProblemCategories");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.ProblemLanguage", b =>
                {
                    b.Property<int>("ProblemLanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProblemLanguageID"));

                    b.Property<int>("LanguageID")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemID")
                        .HasColumnType("integer");

                    b.HasKey("ProblemLanguageID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("ProblemID");

                    b.ToTable("ProblemLanguages");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.RecoveryCode", b =>
                {
                    b.Property<int>("RecoveryCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecoveryCodeID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("RecoveryCodeID");

                    b.HasIndex("UserID");

                    b.ToTable("RecoveryCodes");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<int>("ActiveStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastActiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("path/to/default/profile-picture.jpg");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Newbie");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SecretKey")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.UserPreference", b =>
                {
                    b.Property<int>("UserPreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPreferenceID"));

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserPreferenceID");

                    b.HasIndex("UserID");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.UserSubmission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionID"));

                    b.Property<int?>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageID")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryUsage")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemID")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreAwarded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmissionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SubmittedCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("SubmissionID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("ProblemID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSubmissions");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.AIConversation", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.Problem", "Problem")
                        .WithMany("AIConversations")
                        .HasForeignKey("ProblemID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("AIConversations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.APIKey", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("APIKeys")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.AuditLog", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Feedback", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.Problem", "Problem")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProblemID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.ProblemCategory", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.Category", "Category")
                        .WithMany("ProblemCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorProjBackend.Data.Problem", "Problem")
                        .WithMany("ProblemCategories")
                        .HasForeignKey("ProblemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.ProblemLanguage", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.Language", "Language")
                        .WithMany("ProblemLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorProjBackend.Data.Problem", "Problem")
                        .WithMany("ProblemLanguages")
                        .HasForeignKey("ProblemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.RecoveryCode", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.UserPreference", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.UserSubmission", b =>
                {
                    b.HasOne("SeniorProjBackend.Data.Language", "Language")
                        .WithMany("UserSubmissions")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorProjBackend.Data.Problem", "Problem")
                        .WithMany("UserSubmissions")
                        .HasForeignKey("ProblemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorProjBackend.Data.User", "User")
                        .WithMany("UserSubmissions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Category", b =>
                {
                    b.Navigation("ProblemCategories");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Language", b =>
                {
                    b.Navigation("ProblemLanguages");

                    b.Navigation("UserSubmissions");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.Problem", b =>
                {
                    b.Navigation("AIConversations");

                    b.Navigation("Feedbacks");

                    b.Navigation("ProblemCategories");

                    b.Navigation("ProblemLanguages");

                    b.Navigation("UserSubmissions");
                });

            modelBuilder.Entity("SeniorProjBackend.Data.User", b =>
                {
                    b.Navigation("AIConversations");

                    b.Navigation("APIKeys");

                    b.Navigation("AuditLogs");

                    b.Navigation("Feedbacks");

                    b.Navigation("RecoveryCodes");

                    b.Navigation("UserPreferences");

                    b.Navigation("UserSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
